### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by popopopoporgerge34** [lckt0/DotKill-Unpacker#3]
Assembly info, program file is gone

**Comment by greenozon** [comment]
Confirming

![image](https://github.com/user-attachments/assets/36a3cbde-6488-4c73-ba93-608ae35a0051)

2 files (or maybe more?) are not present in the repo

**Comment by greenozon** [comment]
Recovered missed files
Please add to main branch

[DotKill-missed-files.zip](https://github.com/user-attachments/files/17350248/DotKill-missed-files.zip)

**Comment by lckt0** [comment]
Added, thanks.
